# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright 2024 The SPDX Contributors

name: validate PR

on:
  pull_request

jobs:
  doit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
            python-version: "3.12"
      - name: get spec-parser
        run: |
          git clone --depth=1 --single-branch --branch=main https://github.com/spdx/spec-parser/ ${{ runner.temp }}/spec-parser
          python ${{ runner.temp }}/spec-parser/main.py -h
      - name: run spec-parser to validate
        run: |
          python ${{ runner.temp }}/spec-parser/main.py -n model
