# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright 2024 The SPDX Contributors

name: validate PR

on:
  pull_request

jobs:
  doit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
            python-version: "3.12"
      - name: get spec-parser
        run: |
          git clone --depth=1 --single-branch --branch=main https://github.com/spdx/spec-parser/ ${{ runner.temp }}/spec-parser
          python ${{ runner.temp }}/spec-parser/main.py -h
      - name: run spec-parser to validate
        run: |
          python ${{ runner.temp }}/spec-parser/main.py -n model
